CREATE DATABASE dev_slovo;
CREATE USER slovo WITH PASSWORD '123456';
GRANT ALL PRIVILEGES ON DATABASE dev_slovo to slovo;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;