version: '3'
services:
  nginx:
    image: 'nginx:1.17'
    container_name: slovo-nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/logs:/var/log/nginx
    working_dir: /var/www
    restart: on-failure
    links:
      - app
    depends_on:
      - app
  app:
    build: docker/app
    container_name: slovo-app
    volumes:
      - ./:/var/www
      - ./docker/app/logs:/var/log/php-fpm
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_enable=1
      PHP_IDE_CONFIG: serverName=Docker
      USER: '1000:1000'
    working_dir: /var/www
    restart: on-failure
    links:
      - pg
    depends_on:
      - pg
  pg:
    build: ./docker/pg
    container_name: slovo-pg
    restart: on-failure
    ports:
      - '32772:5432'
    environment:
      POSTGRES_PASSWORD: 123456
  node:
    build: ./docker/node
    container_name: slovo-node
    restart: on-failure
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
    # command: bash -c "yarn && npm run build && npm run start"
    command: bash -c "yarn && npm run dev"
  redis:
    image: redis
    container_name: slovo-redis
    restart: on-failure
    ports:
      - '6379:6379'
